version: '3.8'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    depends_on:
      - cadvisor-exporter

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    ports:
      - 9100:9100
    restart: always
    deploy:
      mode: global

  alertmanager:
    image: prom/alertmanager
    restart: always
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  cadvisor-exporter:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 9200:8080
    restart: unless-stopped
    deploy:
      mode: global

  snmp-exporter:
    image: prom/snmp-exporter
    restart: unless-stopped
    volumes:
      - ./snmp/:/etc/snmp_exporter/
    ports: 
      - 9116:9116
    depends_on:
      - prometheus

#  graphite:
#    image: graphiteapp/graphite-statsd:latest
#    ports:
#    - 8088:80        #Web interface port
#    - 8090:8080      #Port for grafana
#    - 2003:2003
#    - 8126:8125
#    volumes:
#    - ./storage:/opt/graphite/storage
#    environment:
#    - COLLECTD=1
#    - GRAPHITE_DEBUG=1
#    - REDIS_TAGDB=1
#    - BRUBECK=1

# InfluxDB for TrueNAS monitoring
  influxdb:
    image: influxdb:1.8
    ports:
      - 8086:8086
      - 2003:2003
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
    volumes:
#      - ./influx:/var/lib/influxdb2
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
    command: -config /etc/influxdb/influxdb.conf

  grafana:
    image: grafana/grafana
    user: '472'
    restart: always
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    ports:
      - 3000:3000
    depends_on:
      - prometheus
