# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'cadvisor-exporter'
    scrape_interval: 1s
    static_configs:
      - targets: ['cadvisor-exporter:8080']

    dns_sd_configs:
    - names:
      - 'tasks.cadvisor-exporter'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    scrape_interval: 5s

    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: docker
    static_configs:
      - targets: ['192.168.1.1:9323'] # local IP where docker is running

#  - job_name: QNAP
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['192.168.1.2:9100'] # IP container node_exporter which is launched on QNAP

#  - job_name: mysql-exporter
#    static_configs:
#      - targets: ['192.168.121.42:9104'] # container IP addresses with mysql_exporter
   
#  - job_name: windows-exporter
#    static_configs:
#      - targets: ['192.168.1.1:9182', '192.168.1.2:9182','192.168.1.3:9182'] # IP addresses of Windows computers running windows exporter

  - job_name: mikrotik
    static_configs:
      - targets:
        - 192.168.88.1 # target mikrotik IP 
        - 192.168.88.2 # target mikrotik IP 
    metrics_path: /snmp
    params:
      module: [mikrotik]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.1.1:9116 # container IP addresses with snmp_exporter

#  - job_name: 'pushgateway'
#    scrape_interval: 10s
#    dns_sd_configs:
#    - names:
#      - 'tasks.pushgateway'
#      type: 'A'
#     static_configs:
#         - targets: ['node-exporter:9100']

